"""Add player_name and inventory_slots columns

Revision ID: 724c74c32178
Revises: 001
Create Date: 2025-08-19 15:41:06.129970

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "724c74c32178"
down_revision: Union[str, None] = "001"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add columns with nullable=True first
    op.add_column("game_sessions", sa.Column("player_name", sa.String(), nullable=True))
    op.add_column(
        "game_sessions", sa.Column("inventory_slots", sa.JSON(), nullable=True)
    )

    # Set default values for existing rows
    op.execute(
        "UPDATE game_sessions SET player_name = 'Player' WHERE player_name IS NULL"
    )
    op.execute(
        "UPDATE game_sessions SET inventory_slots = '[]'::json WHERE inventory_slots IS NULL"
    )

    # Now make them non-nullable
    op.alter_column("game_sessions", "player_name", nullable=False)
    op.alter_column("game_sessions", "inventory_slots", nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("game_sessions", "inventory_slots")
    op.drop_column("game_sessions", "player_name")
    # ### end Alembic commands ###
