"""Add partial indexes for matchmaking optimization

Revision ID: e355446b06a3
Revises: 01efc3dd88e1
Create Date: 2025-08-20 14:51:56.881455

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e355446b06a3"
down_revision: Union[str, None] = "01efc3dd88e1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "matchmaking_history",
        sa.Column("player_build_id", sa.Integer(), nullable=False),
    )
    op.add_column(
        "matchmaking_history", sa.Column("battle_winner", sa.Integer(), nullable=False)
    )
    op.drop_constraint("unique_recent_match", "matchmaking_history", type_="unique")
    op.create_index(
        "idx_build_performance",
        "matchmaking_history",
        ["opponent_build_id", "battle_winner"],
        unique=False,
    )
    op.create_index(
        "idx_recent_matches", "matchmaking_history", ["matched_at"], unique=False
    )
    op.create_index(
        op.f("ix_matchmaking_history_opponent_build_id"),
        "matchmaking_history",
        ["opponent_build_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_matchmaking_history_player_build_id"),
        "matchmaking_history",
        ["player_build_id"],
        unique=False,
    )
    op.create_foreign_key(
        None, "matchmaking_history", "player_builds", ["player_build_id"], ["id"]
    )
    op.drop_index("idx_matchmaking", table_name="player_builds")
    op.create_index(
        "idx_matchmaking_recent_wins",
        "player_builds",
        ["round_number", "game_version", "win_percent"],
        unique=False,
        postgresql_where=sa.text(
            "created_at > (CURRENT_TIMESTAMP - INTERVAL '7 days') AND battle_won = TRUE"
        ),
    )
    op.create_index(
        "idx_player_recent_builds",
        "player_builds",
        ["user_id", "created_at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_player_recent_builds", table_name="player_builds")
    op.drop_index(
        "idx_matchmaking_recent_wins",
        table_name="player_builds",
        postgresql_where=sa.text(
            "created_at > (CURRENT_TIMESTAMP - INTERVAL '7 days') AND battle_won = TRUE"
        ),
    )
    op.create_index(
        "idx_matchmaking",
        "player_builds",
        ["game_version", "round_number", "win_percent", "created_at"],
        unique=False,
    )
    op.drop_constraint(None, "matchmaking_history", type_="foreignkey")
    op.drop_index(
        op.f("ix_matchmaking_history_player_build_id"), table_name="matchmaking_history"
    )
    op.drop_index(
        op.f("ix_matchmaking_history_opponent_build_id"),
        table_name="matchmaking_history",
    )
    op.drop_index("idx_recent_matches", table_name="matchmaking_history")
    op.drop_index("idx_build_performance", table_name="matchmaking_history")
    op.create_unique_constraint(
        "unique_recent_match",
        "matchmaking_history",
        ["player_user_id", "opponent_build_id"],
    )
    op.drop_column("matchmaking_history", "battle_winner")
    op.drop_column("matchmaking_history", "player_build_id")
    # ### end Alembic commands ###
