"""count runs won on the account

Revision ID: 92319975c175
Revises: c4e07b1a9d36
Create Date: 2026-08-21 14:14:10.468449

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '92319975c175'
down_revision: Union[str, None] = 'c4e07b1a9d36'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('total_runs_won', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'total_runs_won')
    # ### end Alembic commands ###
