"""Pay a run in SnubaCoin, and write down that it finished

Two columns. `game_sessions.finished_at` is when the run ended, and null while
it is still being played -- a run's ending used to be worked out from `lives`
and `wins` every time it was asked for and never recorded, which answers "is it
over" but not "has it been paid for". `users.snuba_coin` is what the account
has been paid, across every run it has ever played.

Written by hand rather than autogenerated. No database here carries an
`alembic_version` table, so there was nothing at this revision to diff against
and autogenerate would have proposed the whole schema.

Revision ID: c4e07b1a9d36
Revises: b7c41d9e2af3
Create Date: 2026-08-21 10:15:00

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c4e07b1a9d36"
down_revision: Union[str, None] = "b7c41d9e2af3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column(
        "game_sessions",
        sa.Column("finished_at", sa.DateTime(), nullable=True),
    )
    # Every run already in the table is left unfinished on purpose. Stamping
    # them would say they had been paid, and none of them have; leaving them
    # null means the next one the player starts settles the last one, which is
    # what an abandoned run gets anyway.
    op.add_column(
        "users",
        sa.Column(
            "snuba_coin",
            sa.Integer(),
            nullable=False,
            server_default=sa.text("0"),
        ),
    )


def downgrade() -> None:
    op.drop_column("users", "snuba_coin")
    op.drop_column("game_sessions", "finished_at")
